services:
  libroo:
    image: 'libroo-website'
    restart: unless-stopped
    volumes:
      - 'sqlite_data:/app/data'
    environment:
      - 'NUXT_DB_FILE_NAME=${NUXT_DB_FILE_NAME:-data/local.db}'
      - 'NUXT_TURNSTILE_SECRET_KEY=${NUXT_TURNSTILE_SECRET_KEY}'
      - 'NUXT_PUBLIC_TURNSTILE_SITE_KEY=${NUXT_PUBLIC_TURNSTILE_SITE_KEY}'
      - 'NUXT_PUBLIC_SCRIPTS_UMAMI_ANALYTICS_SCRIPT_INPUT_SRC=${NUXT_PUBLIC_SCRIPTS_UMAMI_ANALYTICS_SCRIPT_INPUT_SRC}'
      - 'NUXT_PUBLIC_SCRIPTS_UMAMI_ANALYTICS_WEBSITE_ID=${NUXT_PUBLIC_SCRIPTS_UMAMI_ANALYTICS_WEBSITE_ID}'
      - 'NUXT_SITE_URL=${SERVICE_FQDN_LIBROO}'
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '-O-'
        - 'http://0.0.0.0:8080'
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  sqlite_data:
